In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("data.xlsx")

In [3]:
# total len
len(df)

125

In [4]:
#unique
len(df["Primary Used by"].unique())

120

In [5]:
# print duplicates 
df[df.duplicated(['Primary Used by'])]

,CI Name*,Primary Used by,Primary Used by Login,RecCC
28,HC-UT50176N,Tuan Nguyen Thanh (HcP/FCM3),GUU2HC,183200
59,TEZZ1287,Florian Kogler (PS-EC/EFV5),KFL5WI,941700
64,PG1UT0365N,Eu Jin Benjamin Mah (CI/CWR31-AS),MAE1PG1,905903
65,SI-Z0W3X,Denis Haecker (PS/ETT4),DEH1SI,209529
91,HC-UT50476N,Binh Nguyen Duc (HcP/FCM3),GIB1HC,183200

In [6]:
df = df.dropna(how='any',axis=0)

In [7]:
# get unique details
df.drop_duplicates(['Primary Used by'], inplace= True)
print(len(df))

119

In [ ]:
#get the name and get the lasel number

In [9]:
name = "SketchUPPro"

In [10]:
lasel = "124063"

In [11]:
df

,CI Name*,Primary Used by,Primary Used by Login,RecCC
0,BANZ65515,Ravi Shankar Kayampady (BT-IA/ASA-IN),KRY1BAN,903S05
1,MLLZ0486,Henrik Westman (CI/CER2-NE),WNH1MLL,SE6142
2,ML-UT0001C,Ma. Luisa Faller (PT-BE/MKU-AP),FAL5MNL,564240
3,NU3Z1256,Markus Jank (BT-VS/ETP1.1),JAM2NU3,375255
4,SI-Z0O2D,Denis Haecker (PS/ETT4),DEH1SI,209529
...,...,...,...,...
120,JH-C-000GJ,Veronika Mandatova (FCM-Jh),MVE9JH,515650
121,BRGZN0520,Filipa Raimundo (CC-PS/ENG5-Brg),FIR2BRG,815888
122,LOLX0B68,Luca Bopf (HOME/ENG1),BOL8LOL,67C701
123,OWT-C-00002,Scott Piper (AA/LOP2-Owt),PRS1OWT,13C900
124,OWT-C-00003,Charlie Royce (AA/TEF2-Owt),ROC1OWT,13C900

In [12]:
df1 = df.groupby(["RecCC"]).size().reset_index(name='counts')

In [13]:
df1.counts.sum()

119

In [14]:
list1 = list()
list2 = list()

In [15]:
for i in df1["RecCC"]:
    list1.append(i[:3])
    list2.append(i[3:])

In [16]:
df1["RecCC1"] = list1
df1["RecCC2"] = list2

In [17]:
pd.set_option("display.max_rows", 500)

In [18]:
counts = list()

In [19]:
for i in df1["counts"]:
    counts.append(str(i)+"0000")

In [20]:
df1["counts"] = counts

#

In [21]:
df1

         RecCC counts RecCC1   RecCC2
0       047561  10000    047      561
1       05D016  10000    05D      016
2       060874  10000    060      874
3       062545  10000    062      545
4       13C900  90000    13C      900
5       154570  30000    154      570
6       154786  10000    154      786
7       170998  10000    170      998
8       183200  20000    183      200
9       18C955  10000    18C      955
10      201567  20000    201      567
11      201894  10000    201      894
12      209529  60000    209      529
13      211512  30000    211      512
14      211588  10000    211      588
15      211919  10000    211      919
16      213690  10000    213      690
17      251151  10000    251      151
18      257720  10000    257      720
19      280773  10000    280      773
20      287420  10000    287      420
21      287601  20000    287      601
22      287704  80000    287      704
23      287922  10000    287      922
24      295160  10000    295      160
25      372307  10000    372      307
26      372311  10000    372      311
27      375255  10000    375      255
28      38F062  10000    38F      062
29      506803  10000    506      803
30      506875  10000    506      875
31      511451  10000    511      451
32      515650  10000    515      650
33      527920  10000    527      920
34      537120  10000    537      120
35      54F841  10000    54F      841
36      54F847  30000    54F      847
37      564240  10000    564      240
38      586383  10000    586      383
39      61B226  10000    61B      226
40      652050  20000    652      050
41      652S41  10000    652      S41
42      652W41  10000    652      W41
43      667270  10000    667      270
44      667906  10000    667      906
45      67C701  10000    67C      701
46      684031  10000    684      031
47      684159  10000    684      159
48      698250  10000    698      250
49      698272  20000    698      272
50      698301  10000    698      301
51      698307  30000    698      307
52      698396  10000    698      396
53      711399  30000    711      399
54      718940  10000    718      940
55      815192  10000    815      192
56      815888  10000    815      888
57      816830  10000    816      830
58      829510  10000    829      510
59      829620  10000    829      620
60      865910  10000    865      910
61      866958  10000    866      958
62      903S03  30000    903      S03
63      903S04  10000    903      S04
64      903S05  10000    903      S05
65      905903  10000    905      903
66      908777  10000    908      777
67      939140  10000    939      140
68      941700  10000    941      700
69      979860  10000    979      860
70      980220  10000    980      220
71      980443  10000    980      443
72      981540  10000    981      540
73      981661  10000    981      661
74      982314  10000    982      314
75      982427  10000    982      427
76      BR1016  10000    BR1      016
77      NL1265  10000    NL1      265
78      NL3004  10000    NL3      004
79      PL1403  10000    PL1      403
80      SE6142  10000    SE6      142
81  US40144009  10000    US4  0144009

In [22]:
from datetime import datetime

In [23]:
if datetime.now().month < 10:
    month_year = str(datetime.now().year)+"0"+str(datetime.now().month)
else:
    month_year = str(datetime.now().year)+str(datetime.now().month)

month_year

'202005'

In [24]:
final_df = pd.DataFrame()

In [25]:
final_df["x"] = df1["counts"]

In [28]:
final_df["a"] = "XX"
final_df["b"] = month_year

final_df["c"] = ""
final_df["d"] = ""
final_df["e"] = ""

final_df["f"] = "A000"
final_df["g"] = "420"
final_df["h"] = "068"

final_df["i"] = df1["RecCC1"]
final_df["j"] = df1["RecCC2"]
final_df["k"] = lasel
final_df["l"] = ""
final_df["m"] = ""
final_df["n"] = df1["counts"]



del final_df['x']

In [29]:
final_df

     a       b c d e     f    g    h    i        j       k l m      n
0   XX  202005        A000  420  068  047      561  124063      10000
1   XX  202005        A000  420  068  05D      016  124063      10000
2   XX  202005        A000  420  068  060      874  124063      10000
3   XX  202005        A000  420  068  062      545  124063      10000
4   XX  202005        A000  420  068  13C      900  124063      90000
5   XX  202005        A000  420  068  154      570  124063      30000
6   XX  202005        A000  420  068  154      786  124063      10000
7   XX  202005        A000  420  068  170      998  124063      10000
8   XX  202005        A000  420  068  183      200  124063      20000
9   XX  202005        A000  420  068  18C      955  124063      10000
10  XX  202005        A000  420  068  201      567  124063      20000
11  XX  202005        A000  420  068  201      894  124063      10000
12  XX  202005        A000  420  068  209      529  124063      60000
13  XX  202005        A000  420  068  211      512  124063      30000
14  XX  202005        A000  420  068  211      588  124063      10000
15  XX  202005        A000  420  068  211      919  124063      10000
16  XX  202005        A000  420  068  213      690  124063      10000
17  XX  202005        A000  420  068  251      151  124063      10000
18  XX  202005        A000  420  068  257      720  124063      10000
19  XX  202005        A000  420  068  280      773  124063      10000
20  XX  202005        A000  420  068  287      420  124063      10000
21  XX  202005        A000  420  068  287      601  124063      20000
22  XX  202005        A000  420  068  287      704  124063      80000
23  XX  202005        A000  420  068  287      922  124063      10000
24  XX  202005        A000  420  068  295      160  124063      10000
25  XX  202005        A000  420  068  372      307  124063      10000
26  XX  202005        A000  420  068  372      311  124063      10000
27  XX  202005        A000  420  068  375      255  124063      10000
28  XX  202005        A000  420  068  38F      062  124063      10000
29  XX  202005        A000  420  068  506      803  124063      10000
30  XX  202005        A000  420  068  506      875  124063      10000
31  XX  202005        A000  420  068  511      451  124063      10000
32  XX  202005        A000  420  068  515      650  124063      10000
33  XX  202005        A000  420  068  527      920  124063      10000
34  XX  202005        A000  420  068  537      120  124063      10000
35  XX  202005        A000  420  068  54F      841  124063      10000
36  XX  202005        A000  420  068  54F      847  124063      30000
37  XX  202005        A000  420  068  564      240  124063      10000
38  XX  202005        A000  420  068  586      383  124063      10000
39  XX  202005        A000  420  068  61B      226  124063      10000
40  XX  202005        A000  420  068  652      050  124063      20000
41  XX  202005        A000  420  068  652      S41  124063      10000
42  XX  202005        A000  420  068  652      W41  124063      10000
43  XX  202005        A000  420  068  667      270  124063      10000
44  XX  202005        A000  420  068  667      906  124063      10000
45  XX  202005        A000  420  068  67C      701  124063      10000
46  XX  202005        A000  420  068  684      031  124063      10000
47  XX  202005        A000  420  068  684      159  124063      10000
48  XX  202005        A000  420  068  698      250  124063      10000
49  XX  202005        A000  420  068  698      272  124063      20000
50  XX  202005        A000  420  068  698      301  124063      10000
51  XX  202005        A000  420  068  698      307  124063      30000
52  XX  202005        A000  420  068  698      396  124063      10000
53  XX  202005        A000  420  068  711      399  124063      30000
54  XX  202005        A000  420  068  718      940  124063      10000
55  XX  202005        A000  420  068  815      192  124063      10000
56  XX  202005        A000  420  068  815      888  124063      10000
57  XX  202005        A000  420  068  816      830  124063      10000
58  XX  202005        A000  420  068  829      510  124063      10000
59  XX  202005        A000  420  068  829      620  124063      10000
60  XX  202005        A000  420  068  865      910  124063      10000
61  XX  202005        A000  420  068  866      958  124063      10000
62  XX  202005        A000  420  068  903      S03  124063      30000
63  XX  202005        A000  420  068  903      S04  124063      10000
64  XX  202005        A000  420  068  903      S05  124063      10000
65  XX  202005        A000  420  068  905      903  124063      10000
66  XX  202005        A000  420  068  908      777  124063      10000
67  XX  202005        A000  420  068  939      140  124063      10000
68  XX  202005        A000  420  068  941      700  124063      10000
69  XX  202005        A000  420  068  979      860  124063      10000
70  XX  202005        A000  420  068  980      220  124063      10000
71  XX  202005        A000  420  068  980      443  124063      10000
72  XX  202005        A000  420  068  981      540  124063      10000
73  XX  202005        A000  420  068  981      661  124063      10000
74  XX  202005        A000  420  068  982      314  124063      10000
75  XX  202005        A000  420  068  982      427  124063      10000
76  XX  202005        A000  420  068  BR1      016  124063      10000
77  XX  202005        A000  420  068  NL1      265  124063      10000
78  XX  202005        A000  420  068  NL3      004  124063      10000
79  XX  202005        A000  420  068  PL1      403  124063      10000
80  XX  202005        A000  420  068  SE6      142  124063      10000
81  XX  202005        A000  420  068  US4  0144009  124063      10000

In [31]:
mydate = datetime.now()
mydate.strftime("%B")

'May'

In [32]:
filename = "Charging"+"_"+name+"_"+mydate.strftime("%B")+str(datetime.now().year)

In [33]:
filename

'Charging_SketchUPPro_May2020'

In [34]:
final_df.to_excel(f"{filename}.xlsx", header=False, index = False)